<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Anshuman" name="TestNGReporting_Seleneum.demoOne" tests="2" failures="1" timestamp="16 Nov 2015 18:20:39 GMT" time="1.059" errors="0">
  <testcase name="secondTestCase" time="0.004" classname="TestNGReporting_Seleneum.demoOne"/>
  <testcase name="firstTestCase" time="1.055" classname="TestNGReporting_Seleneum.demoOne">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.firstTestCase() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.firstTestCase() didn't finish within the time-out 1000
	at java.lang.Thread.exit(Unknown Source)
]]>
    </failure>
  </testcase> <!-- firstTestCase -->
</testsuite> <!-- TestNGReporting_Seleneum.demoOne -->
